webserver/models.py
from webserver import db

class ImageUpload(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(200), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.String(150), db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('image_set'))

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

webserver/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, EmailField, FileField
from wtforms.validators import DataRequired, Length, EqualTo, Email, regexp

class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다.')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('이메일', validators=[DataRequired(), Email()])

class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

webserver/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_envvar('APP_CONFIG_FILE')

    # ORM
    db.init_app(app)

    #migrate.init_app(app, db)
    from. import models

    # blueprint
    from .views import main_views, image_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(image_views.bp)
    app.register_blueprint(auth_views.bp)

    #filter
    from .filter import format_datetime
    app.jinja_env.filters['datetime'] = format_datetime

    return app

webserver/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from webserver import db
from webserver.forms import UserCreateForm, UserLoginForm
from webserver.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

webserver/views/image_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import ImageUpload
from ..views.auth_views import login_required

bp = Blueprint('image', __name__, url_prefix='/image')

@bp.route('/list')
def _list():
    page = request.args.get('page', type=int, default=1)
    image_list = ImageUpload.query.order_by(ImageUpload.create_date.desc())
    image_list = image_list.paginate(page, per_page=10)
    return render_template('image/image_list.html', image_list=image_list)

@bp.route('/upload/', methods=('POST', ))
def upload():
    if request.method == 'POST':
        _file = request.files['file']
        _file.save('C:\pythonProject1\webserver\static\\' + _file.filename)
        image = ImageUpload(filename=_file.filename, create_date=datetime.now(), user_id=1)
        if image != None:
            db.session.add(image)
            db.session.commit()
            return redirect(url_for('image._list'))

@bp.route('/detail/<int:image_id>/')
@login_required
def detail(image_id):
    image = ImageUpload.query.get_or_404(image_id)
    return render_template('image/image_detail.html', image = image)

@bp.route('/delete/<int:image_id>')
@login_required
def delete(image_id):
    image = ImageUpload.query.get_or_404(image_id)
    if g.user != image.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('image.detail', image_id=image_id))
    db.session.delete(image)
    db.session.commit()
    return redirect(url_for('image._list'))

webserver/views/main_views.py
# 사용자에게 보여질 뷰를 따로 정의하는 곳. 따라서 객체 생성하는 곳 = 인잇이 뚱뚱해지지 않음.
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_server():
    return 'Hello, Server!!'

@bp.route('/')
def index():
    return redirect(url_for('image._list'))

webserver/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>ImageServer</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
{% block content %}
{% endblock %}

<!--JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
{% block script %}
{% endblock %}
</body>
</html>

webserver/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

webserver/templates/image/image_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- flash error -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ image.create_date|datetime }}</h2>
    <div class="card my-auto">
        <img src="{{ url_for('static', filename=image.filename) }}" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"></div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ image.user.username }}</div>
                    <div>{{ image.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == image.user %}
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('image.delete', image_id=image.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

webserver/templates/image/image_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th style="width:50%">파일이름</th>
            <th>사용자</th>
            <th>일시</th>
        </tr>
        </thead>
        <tbody>
        {% if image_list %}
        {% for image in image_list.items %}
        <tr class="text-center">
            <td>{{ image_list.total - ((image_list.page-1) * image_list.per_page) - loop.index0 }}</td>
            <td class="text-start">
                <a href="{{ url_for('image.detail', image_id=image.id) }}">{{ image.filename }}</a>
            </td>
            <td>{{ image.user.username }}</td>
            <td>{{ image.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 -->
    <ul class="pagination justify-content-center">
        <!-- before page-->
        {% if image_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ image_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in image_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != image_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- after page -->
        {% if image_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ image_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- paging -->
</div>
{% endblock %}

webserver/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">MAIN</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }}(로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>